apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab2-api
  template:
    metadata:
      labels:
        app: lab2-api
    spec:
      containers:
      - name: lab2-api
        image: my-lab2-api
        imagePullPolicy: Never
        ports:
        - containerPort: 3000